#base "../../../../cfg/toucahud/tou_specgui_stream.txt"
#base "../../../../cfg/toucahud/tou_spectator_res.txt"
#base "../../../../cfg/toucahud/tou_spectator_bars.txt"
#base "../../../../cfg/toucahud/tou_items_stream.txt"
#base "hudinspectpanel.res"
#base "spectatortournament_hex.res"